tv:
  host: 192.168.68.52
  device_id: ambisync_yaniss01
  auth_key: 6be351f9c5ca1919516df5be99c269cf9f5b334c7b4824f924b8ddb9698c5714
hue:
  bridge_host: 192.168.1.59
  token: SHHCgK8UE4-rUhIZk2wZS2fZvKmW2RMcHWzv9MEu
  client_key: "39646E355A54B5976BD62E5817314374"
  entertainment_group_id: '200'
govee:
  ip: 192.168.68.59
  device: "20:E7:D1:2D:05:46:73:55"
  model: H618A
  brightness: 100  # % — pleine puissance
poll_hz: 3
transition_ds: 2
openrgb_poll_hz: 0
mapping:
- side: left
  light_id: 1
  brightness: 254
- side: right
  light_id: 2
  brightness: 254
